name: Canary Points Fineract Build

on:
  push:
    branches:
      - canary-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: kamiazya/setup-graphviz@v1

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Login to Github Packages Docker
        uses: azure/docker-login@v1
        with:
          login-server: 'docker.pkg.github.com'
          username: ${{ secrets.DOCKER_USERNAME_CANARY }}
          password: ${{ secrets.DOCKER_PASSWORD_CANARY }}

      - name: Build with Gradles
        run: ./gradlew clean bootWar

      - name: Build Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: fiter1/fineract/canary-fineract-app
          username: ${{ secrets.DOCKER_USERNAME_CANARY }}
          password: ${{ secrets.DOCKER_PASSWORD_CANARY }}
          registry: docker.pkg.github.com
          tags: "latest"

      - name: Deploy to server
        run: |
          echo "$CANARY_SERVER_SSH_KEY" > key.pem
          chmod 400 key.pem
          echo "Restart docker container...!!!"
          echo "ssh -i key.pem -o StrictHostKeyChecking=no $CANARY_SERVER_URL 'sudo /root/deploy-fineract.sh'"
        env:
          TEST_SERVER_SSH_KEY: ${{ secrets.CANARY_SERVER_SSH_KEY }}
          TEST_SERVER_URL: ${{ secrets.CANARY_SERVER_URL }}